FROM python:3.9-slim

WORKDIR /app

COPY ./flask/requirements.txt .

RUN pip install -r requirements.txt
RUN pip install gunicorn
COPY ./flask .

EXPOSE 5000

CMD ["gunicorn", "-w", "3", "-b", "0.0.0.0:5000", "app:app"]

