FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc

COPY ./django_app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./django_app .

EXPOSE 8000

CMD ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:8000", "django_app.wsgi:application"]